Todo  review
osamaashraf6/Todo-List-Review pull request #1
Opened 2022-11-07 19:58 UTC by osamaashraf6

## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Set up a new project with webpack.
- [x] Create an index.html file and write your HTML markup here. Create an empty To Do List placeholder.
- [x] Create The index.html file must be set as a template using the HTML Webpack Plugin.💯
- [x] Create an index.js file and set an array of some simple to-do tasks (array of objects).
- [x]  Each task object should contain three keys
- [x] Write a function to iterate over the tasks array and populate an HTML list item element for each task.💯
- [x] On page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
- [x] Create a style.css and set rules for the To-Do List. CSS must be loaded by Webpack Style/CSS Loader.

## Description of the task to be completed 👎 

- HTML
- CSS
- Flexbox
- JavaScript (ES6)
- Use the javascript objects and arrays to store the data for every project.
- Set up the project using webpack.

  
## How should it be tested

Clone the repository
```
git clone https://github.com/osamaashraf6/Todo-list-Review
```
Navigate to the folder
```
cd Todo-list-Review
```
Checkout the branch
```
git todo__review
```

#### Thanks for reviewing my PR 😊

2022-11-07 20:11 UTC, jellywiz commented
### Hello    @osamaashraf6     :wave:   
Good job so far!
You are doing it well 👍🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️
- Correct Github flow ✔️
- Descriptive PR ✔️
- HTML/CSS Best Practice ✔️
- JavaScript Best Practice ✔️
- Professional README file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-07 20:16 UTC, jellywiz requested changes
Here are some of the comments

2022-11-07 20:16 UTC, jellywiz commented on src/style.css
> +/* start universal styles */
I think it would be better if you have not included those in your code, since they are not necessary and doesn't effect the actual website

2022-11-07 20:16 UTC, jellywiz commented on src/index.html
> +    <!-- start icons -->
Same here with comments

2022-11-07 20:16 UTC, jellywiz commented on src/index.html
> +    <!-- start js file -->
Same here with comments

2022-11-07 20:16 UTC, jellywiz commented on src/style.css
> +/* start content styles */
Same here with comments

2022-11-07 20:35 UTC, jellywiz commented
Hi @osamaashraf6  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Good commit messages.
- [x] Descriptive READme file in a professional way.
- [x] No linters errors. 
- [x] Good usage in correcting GitHub flow
- [x] Good code organization.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 14:05 UTC, merged

2022-11-18 14:30 UTC, osamaashraf6 commented
- Thanks 🙏 for reviewing my pull request  I appreciate your review 💯 
### Thanks for reviewing my PR 😊